eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 9000
spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
