eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9000
spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
app:
  config:
    otp: http//:localhost:9090/api/v1/otp
