eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9002
spring:
  application:
    name: FACADE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
app:
  config:
    auth: http://localhost:9000
logging:
  level:
    org.springframework.web: DEBUG
