eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9002
spring:
  application:
    name: FACADE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#  data:
#    redis:
#      database: 0
#      host: localhost
#      port: 6379
#      timeout: 60000
