eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9090
spring:
  application:
    name: OTP-SERVICE
  config:
    import: optional:configserver:http://localhost:8888